# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:SGpldqrDJxg6bx30AmBCq+FQLiGm9TYKAknyLc9CAddB7Rp4c60dUQ==,iv:PLd7lVHlW1B4aYnT5mMWnuUmJF+5xFpCFVUPyVR333Y=,tag:xdtpB7u+L+y+DR/yUhFA/w==,type:str]
sops:
  age:
    - recipient: age1ayl4fp8hazz4ra8nmkrp0r937dl0r22ns4zj0lj7rujzgm5aug6stz7h23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYm54V25kQW4rVHdQa0R6
        K2Q2QVN6UWo0WWNIc0h4OThSOVV3V1lVd0dRCld3Vi9oVWw4MEtsdCtUak1FMHFM
        bmlIR0YyTFFoaEdVRm91bDVpWGFSSFkKLS0tIHg1Z1FONFg2ZVc3a0p5VlU5UWt3
        dC9Uby94bzFSYW81em9relpSdDRvMkEKUTVmMNc23/5rbPUcyIelY8HjZSaEyORt
        x9Z3q1L7k+IEJ4SUMZwgxxmlQGBojhBNqTBnFYf1rpoaTFj6jAWy3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-02T21:36:02Z"
  mac: ENC[AES256_GCM,data:1A8SUGnbJOQWqMF/tCRRIiFni1SgFdOkAXLXibNo5rYz1qGN8Hhk+tYYCuX04AmGiYOPb7/ckK+N8kXZMYdwpC2fPpLAwKQlaxeyEnzC8MDdS2nNP+AvJJ0ZXcEHnaJp2Wn+7poFyFLP+KRvOK/rUo+TXHOfH9mU+JtblZ39GWs=,iv:HEP8fpFBNTbLpGlmm374LJEo/+T2de4jfGhnIWPu+t8=,tag:Y8Gyz9/vz6rWmR8qtUm6kg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
