# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:tXkSkKBgGwEg+ABk5ni1nL1vEyTqUh0qKM6fJ08Y+OE=,iv:A2TSvoSgLz4A2cD/NA10aJZ1nzIzue6UW4YDOEAkkWg=,tag:mwNCyAYKUqU6LevE7Jmj/Q==,type:str]
sops:
  age:
    - recipient: age1ayl4fp8hazz4ra8nmkrp0r937dl0r22ns4zj0lj7rujzgm5aug6stz7h23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTTZUcTNObUwyWHVSd29S
        a1M5QjFhTUFJWS9GYy9zT3d2SmZuS0dvMVdnCndLbTFNNDRQWVhHbndPaU5UMVdS
        YXAxLzFDMjBndC83UHhkakp3WEdPMzQKLS0tIDkrT2VQKzBtR2JSMEo4N2dTR25W
        TDJOYjBrZ3JsOWJNaEI2a2dZOHJtN3cKIwdjeWChZalzK0EdIJfG7f9lBX1yx/jG
        yGdkOeZdl00psOlPbc30zdW5qYqmaDzY2RTiQAal8ISG2Zw13J87Lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-02T21:36:02Z"
  mac: ENC[AES256_GCM,data:4/93t/fAVDVely7m4iuePBrPSO5zErm7VSU2zWH+0xk8h/ib+WFhA06YwqbqN9wzuxKQyXS3sf3iJTXrXHzgONfPOT/DeXhiyutxzjoBGI4LglXpHCOx44nby0WNuPJs2DXsEfNlE1TyfzywSuKabXcjw5tmc3rT/kt99I6PIhc=,iv:SpJBEj0qf0ofHVBkys/2Vy+tMntI35i76eky0FkWegk=,tag:UbXmaGl//rLQcAR3e9EHmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
