# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:mbkoSamz2l74Dwb2nIhyixm5P6sSwhXbGS+8jNyKE9Sy/vAuXLlcYPDYyMaSyglaIRkWTpJTXKvRbf4+ZHr5Aj03cffwWrRkNG4RA8MDaWYO124Igg5XmjXO9VqnAy0Rr6gO3maa48/KBVuA90kh82wB5Z78XJ+6awaXDHvpL+V5yTSYfIwuele0/4tWiGJCaR0JFW+HLf3mrg+GVM23I3/QQNR1YttEDvwrGtDt7bT+9Cde,iv:R2qZ6yfPhqFXWbFsjqip1HuHLA2p3Tx86vinXpWpcmk=,tag:oh26TZj4VvI6LILu+pxmRw==,type:str]
sops:
  age:
    - recipient: age1ayl4fp8hazz4ra8nmkrp0r937dl0r22ns4zj0lj7rujzgm5aug6stz7h23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVklVcGFYQVllMWxmS1hM
        RGJ0RHpvTWEwVTFuaWF4UFVYbHJGVE1EOG1NCjlDclNyR244bjkvM1VsTGtyWFBK
        NWcyeHFVQzdXSXVpZm91YVYvTHBwdG8KLS0tIE5JTFl1VEovdFpndHlXYXhPb2Fk
        cUFpUjZDNHlFMEFMK1BDOXc0aXUxZ2cKYvZZyr4WJxtpf/t5sTjIgYoFjvPTGhdt
        ilrC1W6LN5KW0W4mRZ0YVxLrIwOaBzKrRKjvOrXXsPseh2o1E5pJZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-02T21:36:02Z"
  mac: ENC[AES256_GCM,data:dhP+Iuhum9o5yBaEhD7LGDY7iyfkBNT5veJxi8fK6IwhKkYs23br6IG9hXOgzC8qxILjjav5pAX7puzfEl0UmckMf2HvF+9asVXj9+vcMJotfIheSNKqCyr/Ay5YTGW6/eBrp0Nwx8fMZZIsmg49EMP+IIcTNZciFR9BtPdD2z4=,iv:61JevDb6heAWNJEzzz13VXImMkF4c09ZuP3C7XKosp0=,tag:NZ96tMcTPYqzRMHyHqmpIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
