# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ApAwKFE3s4DkAAc7SSXwptrYRqmaNqd/qu7uWwxZKTyFZvSzjYALsw==,iv:TSpMDAzyLivRXdVOtOqIIt4qvzxX0+Rvyf8Prz5D+ek=,tag:nfCrjOSptBnicqF1v+bnfg==,type:str]
sops:
  age:
    - recipient: age1ayl4fp8hazz4ra8nmkrp0r937dl0r22ns4zj0lj7rujzgm5aug6stz7h23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRmJxdUlpc2orZUZaSWNR
        ekx2L2JDcEtxbTQxNnYySnZmSDFISWV1S2xFCkd0MHpybFNmSVdOSXZ5NGo2VlNN
        LzAxQm9XaERzdCt2QXFqWmVOWnVvc1EKLS0tIG5vNzZ4ZXpBN2RNQ0t1WFg3bmpO
        Ujk1eUxWdnpQSWRIWGc5WURncDlBeGMK15iMca6sPna6L9k70meghaVI/7KtI9Rk
        xxsYH4gb5nQkmZw2qriYlDFLEAyny08hBVmXmHMu+GpoczMwQuV0aQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-02T21:36:02Z"
  mac: ENC[AES256_GCM,data:+inQ/KG6J/hLm4EV472+w3skTFIy0Dsc7KSYf+VJCmMID0L95G/pbalUN3MiMYzD4u1U8oGiHlR8ZZnncM4H6gy1INPh3Oc1EYlhYueVgocTRTNsYTqWUJyG4k15LO7PSwF/W6GsdWLK+C4KHzlk204TetB8/7rf9jz+WRbFyDY=,iv:BRIPsY0+0PixVw85NSUM+5B56i8HgDD/+Fq1TIgIzmw=,tag:VsTl9lGFivdMUDYDTZTu8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
