apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SZJSpfv6OMUojjM=,iv:P4FEx6AKWfttKNEFpEx/EWW33t+G4BsLIJVnbz8jvk0=,tag:YlDjl2jia/4pA6dtKuB8bg==,type:str]
sops:
  age:
    - recipient: age1ayl4fp8hazz4ra8nmkrp0r937dl0r22ns4zj0lj7rujzgm5aug6stz7h23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWDFtaHVRYUQyejFuOFdS
        dWZEamdDd2daSTdKSHlNSi9zakRXWlI4RjBvCmx0VHUxUGtoZVpnMHNwV2l1TVNv
        ZkpPd2hnVjZnYmdKYjBJTFNpZ2hld00KLS0tIHUzWkpMc3BoeDZzeGhsQTFZUWEw
        ZXZySkI2MjQ5K29nNmplZ2lUdGcrMGcKoWQQN9GJ9QLFJ6QJteqh1tAr8WgRGgo+
        APVeQ0/a5HY/HAMT0QE+h8JPX55uuAQGf49MNDm8jBdTPyjDpc+8mA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-02T21:36:01Z"
  mac: ENC[AES256_GCM,data:5SrW1VnAPkzkKoAOtGqfxy/O+EIYo32gUzsb1Swe+DbnvSEClKNN6sD6mOvDakdncdkRb5GoGgDrR2WtrhBUMq4kqpVjNuN14UIlwJzmR++qlsYEiJZ4ITElCdFQbX4irifspvPiAxaMWVUQut8DFc0H2f7URFet2pc/1WFuY4Q=,iv:+SYt5f5TD6ssKFJ9HvdNKWtq73ZZXeNq1vjKidGoppc=,tag:Ca+aAs+0AhTkzAIJUTQF8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
